plugins {
    id 'com.android.application'
}

android {
    namespace 'com.facilitus.app'
    compileSdk 34

    defaultConfig {
        applicationId 'cn.dolit.nexus'
        minSdk 23
        targetSdk 34
        versionCode 9
        versionName '0.9.0'

    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }

    lint {
        abortOnError false
    }
}
